// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates an AI-suggested image of improvements with MINT thread lifts based on a user-uploaded photo.
 *
 * - generateAiImprovements - A function that generates the AI improvements.
 * - AiImprovementsInput - The input type for the generateAiImprovements function.
 * - AiImprovementsOutput - The return type for the generateAiImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiImprovementsInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo of the user, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'    ),
});
export type AiImprovementsInput = z.infer<typeof AiImprovementsInputSchema>;

const AiImprovementsOutputSchema = z.object({
  improvedPhotoDataUri: z
    .string()
    .describe(
      'An AI-generated photo showing potential improvements with MINT thread lifts, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'    ),
});
export type AiImprovementsOutput = z.infer<typeof AiImprovementsOutputSchema>;

export async function generateAiImprovements(input: AiImprovementsInput): Promise<AiImprovementsOutput> {
  return aiImprovementsFlow(input);
}

const aiImprovementsPrompt = ai.definePrompt({
  name: 'aiImprovementsPrompt',
  input: {schema: AiImprovementsInputSchema},
  output: {schema: AiImprovementsOutputSchema},
  prompt: [
    {media: {url: '{{{photoDataUri}}}'}},
    {
      text: `Generate an image showing potential improvements with MINT thread lifts on the provided photo. Focus on lifting and tightening the skin around the jawline, cheeks, and neck, while maintaining a natural appearance.`,
    },
  ],
  config: {
    responseModalities: ['TEXT', 'IMAGE'],
  },
});

const aiImprovementsFlow = ai.defineFlow(
  {
    name: 'aiImprovementsFlow',
    inputSchema: AiImprovementsInputSchema,
    outputSchema: AiImprovementsOutputSchema,
  },
  async input => {
    const {media} = await ai.generate({
      model: 'googleai/gemini-2.5-flash-image-preview',
      prompt: [
        {media: {url: input.photoDataUri}},
        {
          text: `Generate an image showing potential improvements with MINT thread lifts on the provided photo. Focus on lifting and tightening the skin around the jawline, cheeks, and neck, while maintaining a natural appearance.`,
        },
      ],
      config: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    });

    return {improvedPhotoDataUri: media!.url};
  }
);
